# JDK installation on centos8

FROM centos:latest

MAINTAINER MOHD_IZHAR mdizhar@gmail.com

COPY jdk* .

RUN rpm -ivh jdk*

ENV JAVA_HOME /usr/java/jdk1.8.0_171-amd64

ENV JAVA_BIN /usr/java/jdk1.8.0_171-amd64/bin


