# Base image
FROM centos:latest

# Author

MAINTAINER MohdIzhar mdizhar@gmial.com

# adding user

RUN useradd -ms /bin/bash user

# run the CMD instruction

ENTRYPOINT echo "This message will always be  genrated by running ENTRYPOINT instruction using echo command"

# specifying user

USER user
