# Base image
FROM centos:latest

# Author

MAINTAINER MohdIzhar mdizhar@gmial.com

# adding user

RUN useradd -ms /bin/bash user

# run the CMD instruction

CMD echo "This message is geenrated by running CMD instruction using echo command"

# specifying user

USER user
